name: trivy_checkov
on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner 🔍
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          scanners: "misconfig"

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov GitHub Action 🛡️
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          soft_fail: true
          check: CKV_AWS_79
